services:
  app:
    image: php:7.4-fpm
    volumes:
      - ./:/var/www/
    build:
      dockerfile: Dockerfile
    links:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: qbpos
    ports:
      - 3306:3306
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-authentication-plugin=mysql_native_password'
      ]
    volumes:
      - ./docs/web_connector/example.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - app
